/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const LoginTotpLazyImport = createFileRoute('/login/totp')()
const LoginEcodeLazyImport = createFileRoute('/login/ecode')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const LoginTotpLazyRoute = LoginTotpLazyImport.update({
  id: '/login/totp',
  path: '/login/totp',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/totp.lazy').then((d) => d.Route))

const LoginEcodeLazyRoute = LoginEcodeLazyImport.update({
  id: '/login/ecode',
  path: '/login/ecode',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/ecode.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/ecode': {
      id: '/login/ecode'
      path: '/login/ecode'
      fullPath: '/login/ecode'
      preLoaderRoute: typeof LoginEcodeLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/totp': {
      id: '/login/totp'
      path: '/login/totp'
      fullPath: '/login/totp'
      preLoaderRoute: typeof LoginTotpLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login/ecode': typeof LoginEcodeLazyRoute
  '/login/totp': typeof LoginTotpLazyRoute
  '/login': typeof LoginIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login/ecode': typeof LoginEcodeLazyRoute
  '/login/totp': typeof LoginTotpLazyRoute
  '/login': typeof LoginIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/login/ecode': typeof LoginEcodeLazyRoute
  '/login/totp': typeof LoginTotpLazyRoute
  '/login/': typeof LoginIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/ecode' | '/login/totp' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login/ecode' | '/login/totp' | '/login'
  id: '__root__' | '/' | '/login/ecode' | '/login/totp' | '/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginEcodeLazyRoute: typeof LoginEcodeLazyRoute
  LoginTotpLazyRoute: typeof LoginTotpLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginEcodeLazyRoute: LoginEcodeLazyRoute,
  LoginTotpLazyRoute: LoginTotpLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login/ecode",
        "/login/totp",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/login/ecode": {
      "filePath": "login/ecode.lazy.tsx"
    },
    "/login/totp": {
      "filePath": "login/totp.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
