/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const LoginIndexLazyRouteImport = createFileRoute('/login/')()
const LoginTotpLazyRouteImport = createFileRoute('/login/totp')()
const LoginEcodeLazyRouteImport = createFileRoute('/login/ecode')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LoginIndexLazyRoute = LoginIndexLazyRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))
const LoginTotpLazyRoute = LoginTotpLazyRouteImport.update({
  id: '/login/totp',
  path: '/login/totp',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/totp.lazy').then((d) => d.Route))
const LoginEcodeLazyRoute = LoginEcodeLazyRouteImport.update({
  id: '/login/ecode',
  path: '/login/ecode',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login/ecode.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login/ecode': typeof LoginEcodeLazyRoute
  '/login/totp': typeof LoginTotpLazyRoute
  '/login': typeof LoginIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login/ecode': typeof LoginEcodeLazyRoute
  '/login/totp': typeof LoginTotpLazyRoute
  '/login': typeof LoginIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/login/ecode': typeof LoginEcodeLazyRoute
  '/login/totp': typeof LoginTotpLazyRoute
  '/login/': typeof LoginIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/ecode' | '/login/totp' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login/ecode' | '/login/totp' | '/login'
  id: '__root__' | '/' | '/login/ecode' | '/login/totp' | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginEcodeLazyRoute: typeof LoginEcodeLazyRoute
  LoginTotpLazyRoute: typeof LoginTotpLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/totp': {
      id: '/login/totp'
      path: '/login/totp'
      fullPath: '/login/totp'
      preLoaderRoute: typeof LoginTotpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/ecode': {
      id: '/login/ecode'
      path: '/login/ecode'
      fullPath: '/login/ecode'
      preLoaderRoute: typeof LoginEcodeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginEcodeLazyRoute: LoginEcodeLazyRoute,
  LoginTotpLazyRoute: LoginTotpLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
